### PR TITLE
Budget Manager

### PR DESCRIPTION
**Pull request by Gegardus**
This Ruby on Rails capstone project is about building a mobile web application where users can manage their budgets. It provides the possibility to make transactions associated with a category so that one can see how much money is spent and on what. The application named Payment Medium allows the user to:

- register and log in, so that the data is private to them.
- introduce new transactions associated with a category.
- see the money spent on each category.

Payment Medium uses use Postgres as the database and devise for authentication and runs unit and integration tests for most of its important components.

### CODE REVIEW

**Review by Meltrust — CHANGES_REQUESTED** [review]
Hi @Gegardus,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:
- Beautiful project✔️ 
- The app works well✔️ 
- Great use of devise✔️


You can do it

## Required Changes ♻️

- [x] For some reason, it is impossible to see written text on inputs because they are being rendered white.  I need to switch to a dark mode to be able to see written text on inputs. (Tested both on Firefox and Chrome, both on production and development).

Look:

image

Dark mode:
image

Please, kindly correct this little issue so your users can see what they are writing when not on a dark mode. 💪 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Gegardus** [comment]
Thank you @Meltrust. Suggested changes were implemented. Forms placeholders styling was changed.

**Review by rukundoeric — APPROVED** [review]
Hi @Gegardus,

_Excellent job on this project. Keep it up 🎆_

_Congratulations! 🎉  on the splendid job 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

------
>As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by Gegardus** [comment]
Thank you @rukundoeric

**Pull request merged**
